version: '4.0'
services:
    web:
        environment:
            TWITTER_USERNAME: ${TWITTER_USERNAME}
            TWITTER_AUTH_TOKEN: ${TWITTER_AUTH_TOKEN}
            TWITTER_CT0: ${TWITTER_CT0}
            TWITTER_GUEST_ID: ${TWITTER_GUEST_ID}
            TWITTER_BASED: ${TWITTER_BASED}
            TWITTER_SHADE: ${TWITTER_SHADE}
            NEXT_PUBLIC_contractId: ${NEXT_PUBLIC_contractId}
            MPC_PUBLIC_KEY_TESTNET: ${MPC_PUBLIC_KEY_TESTNET}
            MPC_PUBLIC_KEY_MAINNET: ${MPC_PUBLIC_KEY_MAINNET}
            EVM_TOKEN_ADDRESS_BASED: ${EVM_TOKEN_ADDRESS_BASED}
            EVM_TOKEN_ADDRESS_SHADE: ${EVM_TOKEN_ADDRESS_SHADE}
            EVM_MINTER: ${EVM_MINTER}
        platform: linux/amd64 # Explicitly set for TDX
        image: mattdlockyer/based-agent-test:latest@sha256:055c88f43b2c3ca73044dcbf956e08c17e79c323690be634ecaf45bf9c64b066
        container_name: web
        ports:
            - '3000:3000'
        volumes:
            - /var/run/tappd.sock:/var/run/tappd.sock
        restart: always
