version: '4.0'
services:
    web:
        platform: linux/amd64 # Explicitly set for TDX
        image: mattdlockyer/shade-agent-twitter:latest@sha256:ae42a3a274e7ce02c0737b5a214f96354f0984a77fb446d8ca85eb084a4c93eb
        container_name: web
        ports:
            - '3000:3000'
        volumes:
            - /var/run/tappd.sock:/var/run/tappd.sock
        restart: always
